### ISSUE TITLE
bug in Prepare_yahoo_letor_data_set1.py

### ISSUE THREAD

**Issue by wintersurvival** [QingyaoAi/Deep-Listwise-Context-Model-for-Ranking-Refinement#3]
Hi QingyaoAi,
Thanks for releasing code.
In main function of Prepare_yahoo_letor_data_set1.py, the statement:
  RANK_CUT = sys.argv[4]
seems should be modified as:
  RANK_CUT = int(sys.argv[4])
Otherwise, RANK_CUT is a str, for example '10', its ASCII code is much larger than its int type number.

**Comment by QingyaoAi** [comment]
Thank you for pointing it out! I have fixed the problem.
